# Capstone Project - Python

Please note that as per instructions, the dataframes are saved as .csv files which are updated for each tasks.
The most updated dataframe is loaded inorder to perform operations for subsequent tasks.

## Task 1

There are three different tables as given above. Please make three dataframe in python 
and save them as three .csv files. From Task 2 to Task 10, use the saved .csv files only.

In [1]:
import pandas as pd  #importing pandas library
import numpy as np   #importing numpy library

Project = pd.DataFrame({   #Defining Project dataframe
    "ID": ['A001','A002','A003','A004','A005','A002','A005','A003','A001','A003','A001','A004','A004','A005'],
    "Project": ['Project 1','Project 2','Project 3','Project 4','Project 5','Project 6','Project 7','Project 8',
                'Project 9','Project 10','Project 11','Project 12','Project 13','Project 14'],
    "Cost": [1002000, 2000000, 4500000, 5500000, np.nan, 680000, 400000, 350000,
             np.nan, 300000, 2000000, 1000000, 3000000, 200000],
    "Status": ['Finished','Ongoing','Finished','Ongoing','Finished','Failed','Finished',
               'Failed','Ongoing','Finished','Failed','Ongoing','Finished','Finished']
})
Project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [2]:
Employee = pd.DataFrame({ #Defining Employee DataFrame
    'ID':     ['A001', 'A002', 'A003', 'A004', 'A005'],
    'Name':   ['John Alter', 'Alice Luxumberg', 'Tom Sabestine', 'Nina Adgra', 'Amy Johny'],
    'Gender': ['M', 'F', 'M', 'F', 'F'],
    'City':   ['Paris', 'London', 'Berlin', 'Newyork', 'Madrid'],
    'Age':    [25, 27, 29, 31, 30]
})
Employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [3]:
Seniority_level = pd.DataFrame({ #Defining Seniority_level dataframe
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],
    'Designation Level': [2, 2, 3, 2, 3]
})
Seniority_level

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [ ]:
Project.to_csv("Data/Project.csv", index = False) #Saving Project Dataframe as .csv file. giving index = False so that the index numbers are not saved
Employee.to_csv("Data/Employee.csv", index = False) #Saving Employee Dataframe as .csv file
Seniority_level.to_csv("Data/Seniority_level.csv", index = False) #Saving Seniority_level DataFrame as .csv file

## Task 2

The cost column in the dataframe “Project” has some missing values. Your task is to 
compute these missing values. Replace the missing values by running average. You 
should use the “For” loop for this task.

In [ ]:
import pandas as pd
import numpy as np

Project = pd.read_csv('Data/project.csv') #Loading the already saved project dataframe

In [6]:
Project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [7]:
running_sum = 0 #Initializing running sum to 0

running_count = 0 #initializing running count to zero. These variables help in calculating running average

for i in range(len(Project)): #defining for loop over the length of the dataframe
    if pd.isnull(Project.loc[i,'Cost']):   #if condition when the loop iterates over the cell that is nan
        Project.loc[i,'Cost'] = running_sum/running_count #assigns the running average to the nan cell
        running_sum += Project.loc[i, 'Cost'] #The same value is added to the running sum
        running_count += 1 #providing increment to the count of rows for computing average
    else:      #else condition when loop iterates over a cell that is not nan
        running_sum += Project.loc[i,'Cost'] #Value in the current cell added to running sum
        running_count += 1 #providing increment to the count of rows for computing average

Project['Cost'] = Project['Cost'].astype(int) #changing the datatype of the 'Cost' column to integer

Project

      ID     Project     Cost    Status
0   A001   Project 1  1002000  Finished
1   A002   Project 2  2000000   Ongoing
2   A003   Project 3  4500000  Finished
3   A004   Project 4  5500000   Ongoing
4   A005   Project 5  3250500  Finished
5   A002   Project 6   680000    Failed
6   A005   Project 7   400000  Finished
7   A003   Project 8   350000    Failed
8   A001   Project 9  2210312   Ongoing
9   A003  Project 10   300000  Finished
10  A001  Project 11  2000000    Failed
11  A004  Project 12  1000000   Ongoing
12  A004  Project 13  3000000  Finished
13  A005  Project 14   200000  Finished

In [8]:
Project.to_csv('Project_Task2.csv', index=False) #saving the updates made to the Project dataframe

## Task 3

Split the name column in the Employee dataframe into two new columns “First Name”, 
and “Last Name” and remove the older “name” column.

In [ ]:
import pandas as pd

Employee = pd.read_csv('Data/Employee.csv') #Loading the already saved Employee dataframe

In [10]:
Employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [11]:
name_split = Employee['Name'].str.split(" ", n=1, expand = True) #split the name column on " " into FIrst name and Lastname columns

Employee.insert(1, "First Name", name_split[0]) #inserting the 'First Name' column at index 1 after ID
Employee.insert(2, "Last Name", name_split[1]) #inserting the 'Last NAme' column at index 2 after First Name

Employee = Employee.drop('Name', axis= 1) #Removed the Name column after the split

Employee

     ID First Name  Last Name Gender     City  Age
0  A001       John      Alter      M    Paris   25
1  A002      Alice  Luxumberg      F   London   27
2  A003        Tom  Sabestine      M   Berlin   29
3  A004       Nina      Adgra      F  Newyork   31
4  A005        Amy      Johny      F   Madrid   30

In [12]:
Employee.to_csv("Employee_Task3.csv", index= False) #saving the updates made to the Employee dataframe

## Task 4

Join all three dataframes in one single dataframe. Name it “Final”

In [ ]:
import pandas as pd

Project = pd.read_csv('Data/Project_Task2.csv') #Loading the already saved Project dataframe
Employee = pd.read_csv('Data/Employee_Task3.csv')#Loading the already saved Employee dataframe
Seniority_level = pd.read_csv('Data/Seniority_level.csv')#Loading the already saved Seniority_level dataframe

In [14]:
merge1 = pd.merge(left= Project, right= Employee, on = "ID") #Joins the Project and Employee dataframes on ID column as key

Final = pd.merge(left= merge1, right= Seniority_level, on= "ID") #Joins the merged dataframe with the seniority_level dataframe to create Final dataframe

Final

,ID,Project,Cost,Status,First Name,Last Name,Gender,City,Age,Designation Level
0,A001,Project 1,1002000,Finished,John,Alter,M,Paris,25,2
1,A002,Project 2,2000000,Ongoing,Alice,Luxumberg,F,London,27,2
2,A003,Project 3,4500000,Finished,Tom,Sabestine,M,Berlin,29,3
3,A004,Project 4,5500000,Ongoing,Nina,Adgra,F,Newyork,31,2
4,A005,Project 5,3250500,Finished,Amy,Johny,F,Madrid,30,3
5,A002,Project 6,680000,Failed,Alice,Luxumberg,F,London,27,2
6,A005,Project 7,400000,Finished,Amy,Johny,F,Madrid,30,3
7,A003,Project 8,350000,Failed,Tom,Sabestine,M,Berlin,29,3
8,A001,Project 9,2210312,Ongoing,John,Alter,M,Paris,25,2
9,A003,Project 10,300000,Finished,Tom,Sabestine,M,Berlin,29,3
10,A001,Project 11,2000000,Failed,John,Alter,M,Paris,25,2
11,A004,Project 12,1000000,Ongoing,Nina,Adgra,F,Newyork,31,2
12,A004,Project 13,3000000,Finished,Nina,Adgra,F,Newyork,31,2
13,A005,Project 14,200000,Finished,Amy,Johny,F,Madrid,30,3

In [15]:
Final.to_csv("Final.csv", index= False) #Saving the Final dataframe to csv

## Task 5

Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project 
cost only to employees who have finished the projects.

In [16]:
import pandas as pd

Final = pd.read_csv("Final.csv") #Loading the already saved Final dataframe

In [17]:
Final["Bonus"] = Final["Cost"]*.05*(Final["Status"] == "Finished") #Adding a Bonus column with 5% of cost if status is Finished.

Final

,ID,Project,Cost,Status,First Name,Last Name,Gender,City,Age,Designation Level,Bonus
0,A001,Project 1,1002000,Finished,John,Alter,M,Paris,25,2,50100.0
1,A002,Project 2,2000000,Ongoing,Alice,Luxumberg,F,London,27,2,0.0
2,A003,Project 3,4500000,Finished,Tom,Sabestine,M,Berlin,29,3,225000.0
3,A004,Project 4,5500000,Ongoing,Nina,Adgra,F,Newyork,31,2,0.0
4,A005,Project 5,3250500,Finished,Amy,Johny,F,Madrid,30,3,162525.0
5,A002,Project 6,680000,Failed,Alice,Luxumberg,F,London,27,2,0.0
6,A005,Project 7,400000,Finished,Amy,Johny,F,Madrid,30,3,20000.0
7,A003,Project 8,350000,Failed,Tom,Sabestine,M,Berlin,29,3,0.0
8,A001,Project 9,2210312,Ongoing,John,Alter,M,Paris,25,2,0.0
9,A003,Project 10,300000,Finished,Tom,Sabestine,M,Berlin,29,3,15000.0
10,A001,Project 11,2000000,Failed,John,Alter,M,Paris,25,2,0.0
11,A004,Project 12,1000000,Ongoing,Nina,Adgra,F,Newyork,31,2,0.0
12,A004,Project 13,3000000,Finished,Nina,Adgra,F,Newyork,31,2,150000.0
13,A005,Project 14,200000,Finished,Amy,Johny,F,Madrid,30,3,10000.0

In [18]:
Final.to_csv("Final_Task5.csv", index= False) #Saving updates to Final dataframe

## Task 6

Demote the designation level by 1, whose projects have status “fail”. Delete the 
employees record whose designation level is above 4.

In [19]:
import numpy as np
import pandas as pd

Final = pd.read_csv("Final_Task5.csv") #Loading the already saved Final dataframe

In [20]:
failed_ids = Final[Final["Status"] == "Failed"]["ID"].unique() #identifying all IDs which have failed projects

Final["Designation Level"] = np.where( #Demoting the designation level by 1 where any project has status "Failed".
    Final["ID"].isin(failed_ids),     #Designation level is to be treated as a property of the employee
    Final["Designation Level"] - 1,   #So changes in designation level should apply consistently across all projects
    Final["Designation Level"]
)

Final = Final[Final["Designation Level"] < 4] #Deleting records where the designation level is above 4

Final

,ID,Project,Cost,Status,First Name,Last Name,Gender,City,Age,Designation Level,Bonus
0,A001,Project 1,1002000,Finished,John,Alter,M,Paris,25,1,50100.0
1,A002,Project 2,2000000,Ongoing,Alice,Luxumberg,F,London,27,1,0.0
2,A003,Project 3,4500000,Finished,Tom,Sabestine,M,Berlin,29,2,225000.0
3,A004,Project 4,5500000,Ongoing,Nina,Adgra,F,Newyork,31,2,0.0
4,A005,Project 5,3250500,Finished,Amy,Johny,F,Madrid,30,3,162525.0
5,A002,Project 6,680000,Failed,Alice,Luxumberg,F,London,27,1,0.0
6,A005,Project 7,400000,Finished,Amy,Johny,F,Madrid,30,3,20000.0
7,A003,Project 8,350000,Failed,Tom,Sabestine,M,Berlin,29,2,0.0
8,A001,Project 9,2210312,Ongoing,John,Alter,M,Paris,25,1,0.0
9,A003,Project 10,300000,Finished,Tom,Sabestine,M,Berlin,29,2,15000.0
10,A001,Project 11,2000000,Failed,John,Alter,M,Paris,25,1,0.0
11,A004,Project 12,1000000,Ongoing,Nina,Adgra,F,Newyork,31,2,0.0
12,A004,Project 13,3000000,Finished,Nina,Adgra,F,Newyork,31,2,150000.0
13,A005,Project 14,200000,Finished,Amy,Johny,F,Madrid,30,3,10000.0

In [21]:
Final.to_csv("Final_Task6.csv", index = False) #Saving the updates to Final dataframe

## Task 7

Add “Mr.” and “Mrs.” to the first name column and drop the gender column.

In [22]:
import numpy as np
import pandas as pd

Final = pd.read_csv("Final_Task6.csv") #Loading the already saved final dataframe

In [23]:
Final["First Name"] = np.where( #adding .Mr/.Mrs prefix based on gender
    Final["Gender"].str.strip() == "M",
    "Mr. " + Final["First Name"],
    "Mrs. " + Final["First Name"]
)

Final = Final.drop("Gender", axis =1) #Removing the gender column
Final

,ID,Project,Cost,Status,First Name,Last Name,City,Age,Designation Level,Bonus
0,A001,Project 1,1002000,Finished,Mr. John,Alter,Paris,25,1,50100.0
1,A002,Project 2,2000000,Ongoing,Mrs. Alice,Luxumberg,London,27,1,0.0
2,A003,Project 3,4500000,Finished,Mr. Tom,Sabestine,Berlin,29,2,225000.0
3,A004,Project 4,5500000,Ongoing,Mrs. Nina,Adgra,Newyork,31,2,0.0
4,A005,Project 5,3250500,Finished,Mrs. Amy,Johny,Madrid,30,3,162525.0
5,A002,Project 6,680000,Failed,Mrs. Alice,Luxumberg,London,27,1,0.0
6,A005,Project 7,400000,Finished,Mrs. Amy,Johny,Madrid,30,3,20000.0
7,A003,Project 8,350000,Failed,Mr. Tom,Sabestine,Berlin,29,2,0.0
8,A001,Project 9,2210312,Ongoing,Mr. John,Alter,Paris,25,1,0.0
9,A003,Project 10,300000,Finished,Mr. Tom,Sabestine,Berlin,29,2,15000.0
10,A001,Project 11,2000000,Failed,Mr. John,Alter,Paris,25,1,0.0
11,A004,Project 12,1000000,Ongoing,Mrs. Nina,Adgra,Newyork,31,2,0.0
12,A004,Project 13,3000000,Finished,Mrs. Nina,Adgra,Newyork,31,2,150000.0
13,A005,Project 14,200000,Finished,Mrs. Amy,Johny,Madrid,30,3,10000.0

In [24]:
Final.to_csv("Final_Task7.csv", index = False) #Saving the updates to Final Dataframe

## Task 8

Promote designation level by 1 for the employees whose age is more than 29 years using 
IF condition.

In [25]:
import pandas as pd
import numpy as np

Final = pd.read_csv("Final_Task7.csv") #Loading the already saved final dataframe

In [26]:
Final["Designation Level"] = np.where( #promote designation level by 1 where age > 29
    Final["Age"] > 29,
    Final["Designation Level"] + 1,
    Final["Designation Level"]
)

Final

,ID,Project,Cost,Status,First Name,Last Name,City,Age,Designation Level,Bonus
0,A001,Project 1,1002000,Finished,Mr. John,Alter,Paris,25,1,50100.0
1,A002,Project 2,2000000,Ongoing,Mrs. Alice,Luxumberg,London,27,1,0.0
2,A003,Project 3,4500000,Finished,Mr. Tom,Sabestine,Berlin,29,2,225000.0
3,A004,Project 4,5500000,Ongoing,Mrs. Nina,Adgra,Newyork,31,3,0.0
4,A005,Project 5,3250500,Finished,Mrs. Amy,Johny,Madrid,30,4,162525.0
5,A002,Project 6,680000,Failed,Mrs. Alice,Luxumberg,London,27,1,0.0
6,A005,Project 7,400000,Finished,Mrs. Amy,Johny,Madrid,30,4,20000.0
7,A003,Project 8,350000,Failed,Mr. Tom,Sabestine,Berlin,29,2,0.0
8,A001,Project 9,2210312,Ongoing,Mr. John,Alter,Paris,25,1,0.0
9,A003,Project 10,300000,Finished,Mr. Tom,Sabestine,Berlin,29,2,15000.0
10,A001,Project 11,2000000,Failed,Mr. John,Alter,Paris,25,1,0.0
11,A004,Project 12,1000000,Ongoing,Mrs. Nina,Adgra,Newyork,31,3,0.0
12,A004,Project 13,3000000,Finished,Mrs. Nina,Adgra,Newyork,31,3,150000.0
13,A005,Project 14,200000,Finished,Mrs. Amy,Johny,Madrid,30,4,10000.0

In [34]:
Final.to_csv("Final_Task8.csv", index =False) #Saving the updates to Final Dataframe

## Task 9

Add the cost of all projects for each Employee and save it in new dataframe 
“TotalProjCost” with three columns ID, First Name, and Total cost

In [35]:
import pandas as pd

Final = pd.read_csv("Final_Task8.csv") #loading the already saved final dataframe

In [36]:
TotalProjCost = Final.groupby(["ID","First Name"])["Cost"].sum().reset_index() #Doing group by, for calculating sum of cost for each employee

TotalProjCost = TotalProjCost.rename(columns={"Cost" : "Total Cost"}) #Renaming cost column to Total Cost

TotalProjCost

     ID  First Name  Total Cost
0  A001    Mr. John     5212312
1  A002  Mrs. Alice     2680000
2  A003     Mr. Tom     5150000
3  A004   Mrs. Nina     9500000
4  A005    Mrs. Amy     3850500

In [37]:
TotalProjCost.to_csv("TotalProjCost.csv", index = False) #Saving the dataframe as .csv

## Task 10

Print all the employee details whose city name contains the letter “o” in it.

In [38]:
import pandas as pd

Employee = pd.read_csv("Employee_Task3.csv") #Loading the already saved Employee dataframe
TotalProjCost = pd.read_csv("TotalProjCost.csv") #Loading the already saved TotalProjCost dataframe
Final = pd.read_csv("Final_Task8.csv")##Loading the already saved Final dataframe

In [39]:
city_o = Employee[Employee["City"].str.contains("o")] #identifying the employees with letter "o" in the city
city_o = city_o.drop(columns=["First Name"]) #dropping firstname column from employees since this will be taken from TotalProjCost

merged = pd.merge(city_o, TotalProjCost, on="ID", how= "left") #merging with TotalProjCost to get the total project cost for each employee

designation = Final.groupby("ID")["Designation Level"].first().reset_index() #Getting the current designation level of employees

project_count = Final.groupby("ID")["Project"].count().reset_index() #Getting the total number of projects for each selected employee
project_count = project_count.rename(columns={"Project": "Number of Projects"}) 

merged = pd.merge(merged, designation, on ="ID", how = "left") #joining the designation column

merged = pd.merge(merged, project_count, on ="ID", how = "left")

cols = merged.columns.tolist() #Reorder columns

cols.insert(1, cols.pop(cols.index("First Name"))) #move first name column to index 1

Employee_details_o = merged[cols] #reorder dataframe
Employee_details_o

,ID,First Name,Last Name,Gender,City,Age,Total Cost,Designation Level,Number of Projects
0,A002,Mrs. Alice,Luxumberg,F,London,27,2680000,1,2
1,A004,Mrs. Nina,Adgra,F,Newyork,31,9500000,3,3

In [40]:
Employee_details_o.to_csv("Employee_details_o.csv", index = False)